### ISSUE TITLE
Re-enable automatic creation of `option routers` DHCP option

### ISSUE THREAD

**Issue by drkitty** [OSU-Net/cyder#1015]
...possibly suppressible by a checkbox on the creation form or something like that.

**Comment by akeym** [comment]
Could do auto-fill fields based on the network string entered, allowing them to change the default gateway and subnet mask field right there.  It is more likely the gateway field will need to be changed, not the subnet mask though... so maybe the mask option could be a checkbox on the creation form.

**Comment by murrown** [comment]
I'm a bit lost... you want to set it up so that when a person creates a network, they can automatically create a `routers` NetworkAV option? I see that there's a `subnet-mask` attribute too, I'm assuming that should also be created. When you refer to the "gateway field", is that just the value of the `routers` option?

**Comment by akeym** [comment]
Yes, auto-generate routers and subnet-mask attributes.  Routers=gateway in this case.  Again, it may be nice to have the gateway field something auto-filled and editable because that may not be the "standard" IP at the beginning of the network.

**Comment by drkitty** [comment]
As far as I know, `subnet-mask` isn't necessary for IPv4 networks.
