### ISSUE TITLE
Prevent global object add?

### ISSUE THREAD

**Issue by akeym** [OSU-Net/cyder#1017]
This is partially a training issue, but could also be fixed such that it isn't even possible.. hopefully preventing confusion.

As far as I know, and can remember, objects aren't really supposed to be placed in 'global,' with the exception of users.  NOC has run into issues adding things to global like new Ranges, and I suppose domains as well, allowing them to create Systems in global.. and then not being able to edit them because you can't select global from the container list.

How do we make this better?

**Comment by murrown** [comment]
So the problem is, they're going to the global container, and deliberately adding objects to it from the global container's detail view? Heh, I guess I never that someone might do that. It seems like the problem is easily solvable though... Ctnr-Range and Ctnr-Domain are m2m relationships, so just add the Range or Domain to the appropriate container. You don't even have to remove it from global first. I don't think putting an object in global will cause any problems, it just means that only users in global will have permission to use it. That might be a useful feature, I don't know.

**Comment by murrown** [comment]
I mean if we do decide that it's a useful feature then we should probably add the global container back into forms.

But otherwise, it seems to me that the issue is that users think that global is a container like any other, meant for general use. They should pick a different container for newly created ranges and domains.

**Comment by akeym** [comment]
I think the core issue is that when you first create a Range, it automatically puts it in the global container.  We should make the user choose on creation rather than "guess."

**Comment by akeym** [comment]
Or it could be that we basically force creation of Ranges from global, and really it just takes the currently selected Ctnr... since the Network list on the Range form only contains Networks for Ranges that are already added to the currently selected Ctnr.

**Comment by murrown** [comment]
That's not accurate. When you create a new range, it doesn't get put in *any* container, because it's a m2m field. Any given range can have multiple containers and any given container can have multiple ranges. That's also why there isn't a field in the form to "select" a container, because you're supposed to add the range to the container from the container's detail view.

It sounds like people have been creating ranges, but haven't been adding them to any container. So they think the range is in global because global shows everything.

**Comment by akeym** [comment]
Hmm, but I just tried creating a range and it shows up with global in the allowed containers list..

**Comment by murrown** [comment]
In the interface form or something?

**Comment by akeym** [comment]
No, on the detail page of the range I just created (page redirected to after creating the range for the first time)

**Comment by murrown** [comment]
Oh, you're right. Looks like things broke on my end because I needed to migrate my schema.

**Comment by murrown** [comment]
I just created a range in zone.admissions though, and it was added to zone.admissions, not global.

**Comment by akeym** [comment]
But your network list on the range creation form should have been stunted because it doesn't actually show all networks?  I guess it should either not be automatically adding the range to a container, or the list of networks should be every network out there.

**Comment by murrown** [comment]
It shows networks that have ranges in the current container, there were three in zone.admissions. So yeah, it should probably show the full list of networks, but that would be pretty lame to sift through.

What's the problem with creating the range in the global container, from the user's perspective? Adding an object to the global container isn't limiting in any way.

**Comment by akeym** [comment]
Well, then we have issues later with objects just hanging out in global.  And global doesn't have domains assigned to them..  global was really just there so users could "See everything" if they chose, not a dumping ground records because somebody is too lazy to put them in an appropriate container.

**Comment by murrown** [comment]
I agree but that's more our problem than theirs. They shouldn't notice any difference from having a bunch of ranges in the global container. If we decide not to automatically add ranges to containers, they'd have to manually add the range to a container anyway.

**Comment by akeym** [comment]
They want the range to automatically go in to some container initially.. just they should have a choice somehow.  And why have containers if they are just going to put everything in global?  I just see that becoming a huge mess.

**Comment by murrown** [comment]
The point is that if they actually want to use the range, they have to put it in a real container, not global.

But it sounds like we should just show all networks in the range create form and that will solve everything.

**Comment by akeym** [comment]
After talking with some folks in NOC, it sounds like the best course of action is to just not automatically add the created Range to any container at all.  Also, all networks should show up in the list.
