### ISSUE TITLE
Permissions changes on zone detail page

### ISSUE THREAD

**Issue by akeym** [OSU-Net/cyder#1034]
It appears that if you try to remove a user from a container, or change their level, it might not be for the right user (the "are you sure?" prompt shows a different username than the one selected for removal).  This also appears to affect changing user levels on the same container detail page (its actually changing for some other user..

**Comment by murrown** [comment]
I haven't been able to reproduce this error. Everything seems to be working fine for me. I'd thought that maybe, if you delete a user (removing one of the rows) it might cause the table to misalign so that the button links appear in the wrong rows. But even after deleting users, I've only seen the appropriate behavior.

**Comment by akeym** [comment]
Yeah, I have the same issue.. but when I look at production, zone.centralcomputing, I see the bug.  Is this some sort of.. cookie issue? or..?

**Comment by murrown** [comment]
That was the example I needed. Fix is up at https://github.com/OSU-Net/cyder/pull/1035
