### ISSUE TITLE
Users can add interfaces to systems that aren't in their Containers.

### ISSUE THREAD

**Issue by akeym** [OSU-Net/cyder#837]
If you look at a System that isn't in your list of Containers, the create static/dynamic interface buttons are still available.  More interestingly, you can create additional interfaces on said system - and then edit them after creation.  This may be limited based on allowed domains/IPs in the container though.

**Comment by murrown** [comment]
Let me turn it into a question of state... should it be possible to have a System with interfaces in two different containers? Currently Systems have no container field (for good reason?), so they only appear in a certain container because their interfaces do. So should all of a System's interfaces belong to the same container, or should systems be given a many-to-many relationship with containers?

**Comment by akeym** [comment]
"all of a System's interfaces belong to the same container"

**Comment by murrown** [comment]
Alright. I don't think we can get around giving a container field to Systems though.

**Comment by drkitty** [comment]
Couldn't you just add some validation in `System.clean` that ensures all interfaces have the same container?

**Comment by murrown** [comment]
I suppose so but that would be counter to how the relationship between Systems and Containers works in a functional sense. We'd be emulating the constraint that each System has exactly one container, instead of just implementing it in the schema.
