### ISSUE TITLE
Supernets

### ISSUE THREAD

**Issue by akeym** [OSU-Net/cyder#977]
A new object (likely) is needed in Cyder to satisfy the documentation needs of NOC.  This is the concept of a "Supernet" or "Allocation".  This will essentially be a grouping of networks, contained within the IP block specified on the Supernet - similar to how Ranges work with relation to Networks.  The fields needed for a Supernet are name, description, and network/mask.  Supernets can be defined after their child networks have been created.  Existing child Networks should be automatically added to a Supernet upon creation if they are in the defined network/mask.  Child Networks cannot span multiple Supernets, nor should they be allowed to extend outside of the network block specified on the Supernet.  There is a chance that NOC will want to move the definition of VRF from the Network model to Supernet - but I need to verify this.  Supernets do not have heirarchy.  Supernets to not dictate how builds operate, and are only for documentation purposes.

**Comment by murrown** [comment]
I'm assuming Supernets cannot overlap with each other.

**Comment by murrown** [comment]
Should Supernets have attributes, meaning SupernetAV objects?

**Comment by murrown** [comment]
>Existing child Networks should be automatically added to a Supernet upon creation if they are in the defined network/mask.

I'd like to clarify this specification. Rather than storing the relationship between Networks and Supernets, how about we simply allow the related Networks to be accessed from the Supernet? We can easily determine the Networks contained in a Supernet with a simple query, without having to do all that bookkeeping.

Of course the other validation would also remain, in the event that a Supernet/Network is created or resized, we would check that no boundaries are being crossed.

Since "Supernets can be defined after their child networks have been created", I'm assuming that child networks don't need to be associated with a Supernet object.

**Comment by akeym** [comment]
I'm not sure about attributes.  I do feel we'll need to add additional columns to the db/model later though for documentation purposes - but I don't think these will need to be attributes.  I'll need to query further about this to see what is needed.

The relationship doesn't need to be stored, it can be inferred by network/supernet masks.  It sounds like you're on the right track.  And to your last question, yes, they do not need to be associated with a supernet.
